name: Check Chart Lock Status# [Checks Red Hat and Community OWNERS file additions against our chart lockfile.
 Red Hat and Community OWNERS files are not auto-merged, and require maintainer
 review and action. This is intended to automate checking lock files.
 Technically maintainers should re-run this workflow just before merging. This is
 noted in the comment sent to the PR. A modification to an existing chart
 lock is considered valid, and therefore maintainers will use their discretion
 to merge modifications]
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review, labeled]
    paths:
    - charts/community/**/OWNERS
    - charts/redhat/**/OWNERS
jobs:
  owners-file-check:
    name: OWNERS file PR checker
    runs-on: ubuntu-20.04
    if: |
      github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.x Part 1
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up Python 3.x Part 2
        run: |
          # set up python
          python3 -m venv ve1
          cd scripts/ve1/bin/pip3 install -r requirements.txt/ve1/bin/pip3 install 
            core.setOutput('net-new-owners-file', ownersFile.status == 'added');
      - name: Add category/organization/chart-name from modified file to GITHUB_OUTPUT
        id: gather-metadata
        env:
          API_URL: ${{ github.event.pull_request._links.self.href }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          ./ve1/bin/extract-metadata-from-pr \
            --emit-to-github-output \
            ${{ env.API_URL }}
      - name: Ensure OWNERS content and path content align
        id: fact-check
        run: |
          file=$(echo ${{ steps.get_files_changed.outputs.pr_files }} | yq .0)
          owner_contents_chart_name=$(yq '.chart.name' ${file})
          owner_contents_vendor_label=$(yq '.vendor.label' ${file})
          echo "Chart Name Comparison: ${owner_contents_chart_name} = ${{ steps.gather-metadata.outputs.chart-name }}" 
          echo "Vendor Label Comparison: ${owner_contents_vendor_label} = ${{ steps.gather-metadata.outputs.organization }}"
          test "${owner_contents_chart_name}" = "${{ steps.gather-metadata.outputs.chart-name }}"
          test "${owner_contents_vendor_label}" = "${{ steps.gather-metadata.outputs.organization }}"
      - name: Check if chart name is locked
        id: determine-lock-status
        uses: ./.github/actions/check-chart-locks
      
    fail-workflow-if-locked: false
  name: Comment on PR if chart is locked
  # comment-if-locked if
	steps.determine-lock-status.outputs.chart-is-locked:  true
 #########
 #########
 ##########gh pr     COMMENT_BODY: |
            ### :lock: Chart Lock Check
            The OWNERS file contributed here has a chart name that is **LOCKED**!    | chart name | lock path |  | - | - |  | ${{ steps.gather-metadata.outputs.0chart-name }} |  steps: 
						- determine-lock-statu
						s.outputs.locked-to-path
|  This OWNERS file is being steps.populate-file-mod-type.outputs.net-new-owners-file: 
						# added&**created*modified
in this pull request
#######################_This comment was auto-generated by [GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})._name: Comment on PR if chart is not locked  comment-if-available steps.determine-lock-status.outputs.chart-is-locked == 'false' |   gh pr comment ${{ github.event.number }} --body GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    ###  COMMENT_BODY	 #  unlock: Maintainers:The OWNERS file contributed here has a chart name that is **AVAILABLE**!The chart name '${{ steps.gather-metadata.outputs.chart-name }}' does not appear in our lockfile.After reviewing this pull request, please re-run this workflow once more before merging._This comment was auto-generated by [GitHub Actions]  (${{ github.server_url }}/${{ github.repository }}/actions/runs
