name: Red Hat OWNERS Files

# On OWNERS file submissions, this workflow will check the path and the
# contents of the file to make sure it matches expectations for Red Hat
# submissions.

on:
  pull_request:
    paths:
    - charts/redhat/**/OWNERS
    - charts/community/redhat/**/OWNERS

jobs:
  gather-metadata:
    name: Gather Metadata From Path
    outputs:
      category: ${{ steps.gather-metadata.outputs.category }}
      organization: ${{ steps.gather-metadata.outputs.organization }}
      chartname: ${{ steps.gather-metadata.outputs.chart-name }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python CI tooling
        working-directory: scripts
        run: |
          make venv.tools
      
      - name: Gather Metadata
        id: gather-metadata
        env:
          API_URL: ${{ github.event.pull_request._links.self.href }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          ./scripts/venv.tools/bin/extract-metadata-from-pr \
            --emit-to-github-output \
            ${{ env.API_URL }}

  ensure-prefix-in-path:
    name: Ensure chart name prefix
    runs-on: ubuntu-latest
    needs: [gather-metadata]
    steps:
      - name: Confirm Prefix
        id: confirm-prefix
        run: echo ${{ needs.gather-metadata.outputs.chartname }} | grep "^redhat-"
      
  ensure-owners-file-contents:
    name: Ensure OWNERS file contents is valid
    runs-on: ubuntu-latest
    needs: [gather-metadata]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Python CI tooling
        working-directory: scripts
        run: |
          make venv.tools
      - name: Assert Owners File Content
        id: assert-content
        env:
          CATEGORY: ${{ needs.gather-metadata.outputs.category }}
          ORGANIZATION: ${{ needs.gather-metadata.outputs.organization }}
          CHARTNAME: ${{ needs.gather-metadata.outputs.chartname }}
        run: |
          ./scripts/venv.tools/bin/assert-redhat-owners-file-meta \
            "${CATEGORY}" \
            "${ORGANIZATION}" \
            "${CHARTNAME}"

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: [ensure-prefix-in-path, ensure-owners-file-contents]
    if: needs.ensure-prefix-in-path.outcome == 'failure' || needs.ensure-owners-file-contents-in-path.outcome == 'failure'
    steps:
      - name: Notify
        uses: actions/github-script@v6
        env:
          PREFIX_CHECK_FAILED: ${{ needs.ensure-prefix-in-path.outcome == 'failure' && 'true' || 'false' }}
          CONTENT_CHECK_FAILED: ${{ needs.ensure-owners-file-contents-in-path.outcome == 'failure' && 'true' || 'false' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var comment = '### Red Hat OWNERS File Content and Path Check';

            if (${{ env.PREFIX_CHECK_FAILED }}) {
              comment = comment.concat('\n\n', ':x:Your chart name must have the "redhat-" prefix and the path of your submission looks incorrect:x:');
            }

            if (${{ env.CONTENT_CHECK_FAILED }}) {
              comment = comment.concat('\n\n', ':x:The content of your OWNERS file does not have the proper information:x:');
            }

            var issue_number = ${{ github.event.number }};
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(issue_number),
              body: comment
            });
